---
version: 3
images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest

dependencies:
  galaxy: collections/requirements.yml
  python:
    - azure-identity
    - azure-mgmt-compute
    - azure-mgmt-network
    - azure-mgmt-resource
    - azure-mgmt-storage
    - msrestazure
  system:
    - gcc [platform:rpm]
    - python3-devel [platform:rpm]
    - libffi-devel [platform:rpm]
    - openssl-devel [platform:rpm]

options:
  package_manager_path: /usr/bin/microdnf
